# Generated by Django 3.1.7 on 2021-03-27 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0003_auto_20210327_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='createdon',
        ),
    ]
