# Generated by Django 3.1.7 on 2021-03-27 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0003_auto_20210326_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
