# Generated by Django 3.1.7 on 2021-03-27 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0004_remove_product_createdon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='user',
        ),
    ]
